name: Deploy Terraform state bucket

on:
  workflow_dispatch:

jobs:
  deploy:
    name: 'Deploy Terraform state bucket'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy state bucket
        run: |
          set -a 
          source github-actions-terraform/.env.backend
          az login --service-principal \
            --username ${{ secrets.ARM_CLIENT_ID }} \
          az group create \
            --location $TF_VAR_location --name $TF_VAR_state_resource_group_name
          az storage account create \
            --name $TF_VAR_state_storage_account_name \
            --g $TF_VAR_state_resource_group_name \
            --location $TF_VAR_location \
            --sku Standard_LRS \
            --allow-blob-public-access false
          az storage container create \
            --name tfstate \
            --account-name $TF_VAR_state_storage_account_name
